// <auto-generated />
using CQRS_ASP.NETCore6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CQRS_ASP.NETCore6.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20230701114756_student_data_added")]
    partial class student_data_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CQRS_ASP.NETCore6.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            Degree = "Master",
                            Name = "Murad",
                            Surname = "Aliyev",
                            University = "AzTU"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Degree = "Master",
                            Name = "Elshad",
                            Surname = "Babayev",
                            University = "AzTU"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Degree = "Master",
                            Name = "Farid",
                            Surname = "Fahiyev",
                            University = "ADNSU"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
